### ISSUE TITLE
Forge and Plugin server API problem

### ISSUE THREAD

**Issue by TheHecateII** [Romitou/MongoSK#69]
### 🔖 Versions

```
MongoSK : 2.3.0

Skript : 2.6.3
```

### ✒️ Description

After several tests with API allowing Mod and plugin like Mohist or Magma the addons always send me the same error when I connect to the database

But when I use a more conventional version like Paper-spigot or Tacos-spigot the addons work

### ⚙️ Expected behavior

The server is supposed to return a message indicating that it has successfully connected to the database

### 🔎 Steps to reproduce

Just reload a skript using the syntax of the addons

### 📸 Errors or screenshots

```
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! [Skript] Severe Error:
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Something went horribly wrong with Skript.
[00:29:43 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:29:43 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:29:43 ERROR]: #!#! Here is full list of them:
[00:29:43 ERROR]: #!#! MongoSK v2.3.0 (https://github.com/Romitou/MongoSK)
[00:29:43 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:29:43 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:29:43 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:29:43 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:29:43 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:29:43 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Stack trace:
[00:29:43 ERROR]: #!#! java.lang.NoClassDefFoundError: fr/romitou/mongosk/libs/driver/Jep395RecordCodecProvider
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.libs.driver.MongoClientSettings.<clinit>(MongoClientSettings.java:63)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.skript.expressions.ExprMongoServer.get(ExprMongoServer.java:85)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.skript.expressions.ExprMongoServer.get(ExprMongoServer.java:29)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScript$7(ScriptLoader.java:811)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:834)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[00:29:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:29:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[00:29:43 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:29:43 ERROR]: #!#! Caused by: java.lang.ClassNotFoundException: Failed to remap class fr.romitou.mongosk.libs.driver.Jep395RecordCodecProvider
[00:29:43 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:229)
[00:29:43 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:137)
[00:29:43 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110)
[00:29:43 ERROR]: #!#!     at java.lang.ClassLoader.loadClass(Unknown Source)
[00:29:43 ERROR]: #!#!     at java.lang.ClassLoader.loadClass(Unknown Source)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.libs.driver.MongoClientSettings.<clinit>(MongoClientSettings.java:63)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.skript.expressions.ExprMongoServer.get(ExprMongoServer.java:85)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.skript.expressions.ExprMongoServer.get(ExprMongoServer.java:29)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScript$7(ScriptLoader.java:811)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:834)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[00:29:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:29:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[00:29:43 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:29:43 ERROR]: #!#! Caused by: java.lang.IllegalArgumentException
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistClassRepo.findClass0(MohistClassRepo.java:26)
[00:29:43 ERROR]: #!#!     at net.md_5.specialsource.repo.CachingRepo.findClass(CachingRepo.java:46)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.findNormalParents(MohistInheritanceProvider.java:52)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.fineParents(MohistInheritanceProvider.java:23)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:16)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistInheritanceProvider.getParents(MohistInheritanceProvider.java:10)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistJarMapping.tryClimb(MohistJarMapping.java:227)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.mapMethodName(MohistJarRemapper.java:148)
[00:29:43 ERROR]: #!#!     at net.md_5.specialsource.UnsortedRemappingMethodAdapter.visitMethodInsn(UnsortedRemappingMethodAdapter.java:115)
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1496)
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1032)
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
[00:29:43 ERROR]: #!#!     at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:174)
[00:29:43 ERROR]: #!#!     at com.mohistmc.bukkit.nms.remappers.MohistJarRemapper.remapClassFile(MohistJarRemapper.java:156)
[00:29:43 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:193)
[00:29:43 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:137)
[00:29:43 ERROR]: #!#!     at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:110)
[00:29:43 ERROR]: #!#!     at java.lang.ClassLoader.loadClass(Unknown Source)
[00:29:43 ERROR]: #!#!     at java.lang.ClassLoader.loadClass(Unknown Source)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.libs.driver.MongoClientSettings.<clinit>(MongoClientSettings.java:63)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.skript.expressions.ExprMongoServer.get(ExprMongoServer.java:85)
[00:29:43 ERROR]: #!#!     at fr.romitou.mongosk.skript.expressions.ExprMongoServer.get(ExprMongoServer.java:29)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:99)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:274)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:50)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.runTrigger(EvtScript.java:88)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.events.EvtScript.register(EvtScript.java:68)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScript$7(ScriptLoader.java:811)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:834)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:526)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:418)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:434)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:525)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:469)
[00:29:43 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:786)
[00:29:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[00:29:43 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:422)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:831)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778)
[00:29:43 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624)
[00:29:43 ERROR]: #!#!     at java.lang.Thread.run(Unknown Source)
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Version Information:
[00:29:43 ERROR]: #!#!   Skript: 2.6.3 (latest)
[00:29:43 ERROR]: #!#!     Flavor: skriptlang-github
[00:29:43 ERROR]: #!#!     Date: 00:55:22.847925631
[00:29:43 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[00:29:43 ERROR]: #!#!   Minecraft: 1.12.2
[00:29:43 ERROR]: #!#!   Java: 1.8.0_341 (Java HotSpot(TM) 64-Bit Server VM 25.341-b10)
[00:29:43 ERROR]: #!#!   OS: Windows 11 amd64 10.0
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Server platform: Paper
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Current node: null
[00:29:43 ERROR]: #!#! Current item: null
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Thread: Server thread
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! Language: english
[00:29:43 ERROR]: #!#! Link parse mode: DISABLED
[00:29:43 ERROR]: #!#!
[00:29:43 ERROR]: #!#! End of Error.
[00:29:43 ERROR]: #!#!
```

**Comment by TheHecateII** [comment]
Mohist claqué au sol s/o Magma et la 1.16.5
